version: "2"

services:      
  db:
    image: mariadb:12.2@sha256:6a4c4bbf0447c2247801309513fcc0dd17c3f35390368139ce419387fdd1144d
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_DATABASE=temp_db

  adminer:
    image: adminer@sha256:832668141a338ba93dd7bbf5ee4f5f351d98088b959719cf82b2bca785c7e08c
    depends_on:
      - db
    ports:
      - 8000:8080
  
  spring:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      # required arguments
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/temp_db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      # optional arguments
      # - SERVER_PORT=8090
      # - DEBUG=true
      # - SPRING_THYMELEAF_CACHE=false
      # - LOGGING_LEVEL_WEB=DEBUG
    # network_mode: host
    ports: 
      - 8080:8080
